// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtx22oOIA6aFREwLNyaZ08NKAU7qESEkE',
    appId: '1:863666328369:web:f36c72643f1239872f1610',
    messagingSenderId: '863666328369',
    projectId: 'foodapp-5a57b',
    authDomain: 'foodapp-5a57b.firebaseapp.com',
    storageBucket: 'foodapp-5a57b.firebasestorage.app',
    measurementId: 'G-3VXYNRHB5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcmelSSBS6drqV82gsrWZQCxFZ11-IHR8',
    appId: '1:863666328369:android:a040bde07451235d2f1610',
    messagingSenderId: '863666328369',
    projectId: 'foodapp-5a57b',
    storageBucket: 'foodapp-5a57b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5JVz6yViZjWfnFqM1963J8LsmNfmfqIc',
    appId: '1:863666328369:ios:e98037a059ef01672f1610',
    messagingSenderId: '863666328369',
    projectId: 'foodapp-5a57b',
    storageBucket: 'foodapp-5a57b.firebasestorage.app',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5JVz6yViZjWfnFqM1963J8LsmNfmfqIc',
    appId: '1:863666328369:ios:e98037a059ef01672f1610',
    messagingSenderId: '863666328369',
    projectId: 'foodapp-5a57b',
    storageBucket: 'foodapp-5a57b.firebasestorage.app',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtx22oOIA6aFREwLNyaZ08NKAU7qESEkE',
    appId: '1:863666328369:web:14b7854cbc6545d92f1610',
    messagingSenderId: '863666328369',
    projectId: 'foodapp-5a57b',
    authDomain: 'foodapp-5a57b.firebaseapp.com',
    storageBucket: 'foodapp-5a57b.firebasestorage.app',
    measurementId: 'G-3Y0ZTQJXZ3',
  );
}
